services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: WheelsRUs_Frontend
    ports:
      - "5173:80"
    env_file:
      - .env.prod
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: WheelsRUs_Backend
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
  mongodb:
    image: mongo:7
    container_name: summer-mongodb
    expose:
      - "27018"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  redis:
    image: redis:7-alpine
    container_name: summer-redis
    expose:
      - "6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: summer-rabbitmq
    expose:
      - "5672"
      - "15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongodb_data:
  redis_data:
