server{
    listen 80;
    server_name WHEELSRUS_Frontend;
    root /usr/share/nginx/html;
    index index.html index.html index.php;

    location / {
        try_files $uri $uri/ index.html;
        add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload;';
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options "SAMEORIGIN";
        add_header Referrer-Policy "strict-origin";
        add_header Permission-Policy "geolocation=(), midi=(), sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self)";
        add_header Content=Security-Policy "default-src 'self'; font-src *; img-src * data:; script-src *; style-src *";

    }

    location /nginx/test{
        return 200 "NGINX text ran successfully";
    }
}