server{
    listen 80;
    server_name sanrosebhetuwal.com.np www.sanrosebhetuwal.com.np;
    root /usr/share/nginx/html;
    index index.html index.html index.php;

    location / {
        try_files $uri $uri/ index.html;
        add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload;';
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options "SAMEORIGIN";
        add_header Referrer-Policy "strict-origin";
        add_header Permission-Policy "geolocation=(), midi=(), sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self)";
        add_header Content-Security-Policy "default-src 'self'; font-src *; img-src * data:; script-src *; style-src *";

    }

    location /nginx/test{
        return 200 "NGINX text ran successfully";
    }

    location /api/ {
        proxy_pass http://backend:3000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
