server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app
    static_configs:
      - targets: [localhost]
        labels:
          job: wheelsonfire
          app: backend
          __path__: /var/log/app/combined.json

    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: timestamp
            message: message
            stack: stack
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: RFC3339Nano

  - job_name: app-errors
    static_configs:
      - targets: [localhost]
        labels:
          job: wheelsonfire
          app: backend
          type: error
          __path__: /var/log/app/error.json

    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: timestamp
            message: message
            stack: stack
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
